sonar.projectKey=my_platform_core
sonar.projectName=My Platform Core
sonar.sources=apps,libs
sonar.tests=apps,libs
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/migrations/**,**/*.config.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.base.json